sudo: false
language: cpp
os: linux
compiler:
    - gcc
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.9
before_install:
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
    - sudo apt-get update -qq
install:
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
before_script:
    - mkdir obj
    - mkdir lib
script:
    - $CXX --version
    - make compile
    - make build
    - make clean
after_script:
    - rmdir obj
    - rmdir lib